spring:
  application:
    name: AuthSystem

  datasource:
    url: jdbc:mysql://localhost:3306/auth_app?createDatabaseIfNotExist=true
    username: yash
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - email
              - profile
              - openid

          github:
            client-id: ${GITHUB_CLIENT_ID:}
            client-secret: ${GITHUB_CLIENT_SECRET:}
            scope:
              - user:email
              - read:user
            #/ login/oauth2/code/github


server:
  port: 8090

security:
  jwt:
    secret: ${JWT_SECRET:}
    issuer: ${JWT_ISSUER:api.auth.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refreshtoken-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-hhtp-only: ${JWT_HTTP_COOKIE_ONLY:TRUE}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}

logging:
  level:
    org.springframework.security: DEBUG


app:
  auth:
    frontend:
      success-url: http://localhost:5173/auth/success
      failure-url: http://localhost:5173/auth/failure


